#spring.profiles.active: local
server:
  port: 80
  #ssl:
  #  enabled: true # Uses self-signed certificate because no key-store configuration is specified.

internal.lb.uri: http://localhost
spring:
  cloud:
    gateway:
      routes:
        - id: empleados
          uri: ${internal.lb.uri}:9000
          predicates:
            - Path=/api/empleado**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: productos
          uri: ${internal.lb.uri}:9001
          predicates:
            - Path=/api/producto**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: proveedores
          uri: ${internal.lb.uri}:9002
          predicates:
            - Path=/api/proveedor**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
